# src/AppBundle/Resources/config/services.yml
services:
    sonata.admin.post:
        class: AppBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - AppBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
#    enuygun_blog.example:
#        class: Enuygun\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]